import type { Field, Column } from "./components";
export interface Module {
  key: string;
  title: string;
  singular: string;
  description: string;
  permission: string;
  columns: Column[];
  fields: Field[];
}
const name = { key: "name", label: "Nombre completo", required: true };
const active = {
  key: "active",
  label: "Registro activo",
  type: "checkbox",
  default: true,
};
export const modules: Record<string, Module> = {
  patients: {
    key: "patients",
    title: "Pacientes",
    singular: "paciente",
    description: "Un directorio conectado con su agenda y atención.",
    permission: "patients",
    columns: [
      { key: "name", label: "Paciente" },
      { key: "folio", label: "Expediente" },
      { key: "phone", label: "Contacto" },
      { key: "birthDate", label: "Nacimiento" },
      { key: "active", label: "Estado" },
    ],
    fields: [
      name,
      {
        key: "curp",
        label: "CURP",
        required: true,
        hint: "18 caracteres. Sin espacios.",
      },
      {
        key: "birthDate",
        label: "Fecha de nacimiento",
        type: "date",
        required: true,
      },
      {
        key: "sex",
        label: "Sexo",
        options: ["Femenino", "Masculino", "Otro", "No especificado"],
        required: true,
      },
      { key: "phone", label: "Teléfono", required: true },
      { key: "email", label: "Correo", type: "email" },
      { key: "address", label: "Domicilio" },
      { key: "emergencyContact", label: "Contacto de emergencia" },
      { key: "companyId", label: "Empresa asociada", lookup: "companies" },
      active,
    ],
  },
  staff: {
    key: "staff",
    title: "Equipo médico y personal",
    singular: "integrante",
    description: "Especialidades, turnos y disponibilidad del equipo.",
    permission: "staff",
    columns: [
      { key: "name", label: "Integrante" },
      { key: "kind", label: "Área" },
      { key: "specialty", label: "Especialidad" },
      { key: "startsAt", label: "Inicio de jornada" },
      { key: "active", label: "Estado" },
    ],
    fields: [
      name,
      {
        key: "kind",
        label: "Tipo",
        options: ["Médico", "Enfermería", "Auxiliar", "Administrativo"],
        default: "Médico",
        required: true,
      },
      {
        key: "specialty",
        label: "Especialidad / área",
        default: "Medicina general",
        required: true,
      },
      { key: "license", label: "Cédula profesional" },
      { key: "phone", label: "Teléfono" },
      { key: "email", label: "Correo", type: "email" },
      {
        key: "startsAt",
        label: "Inicio de jornada",
        type: "time",
        default: "08:00",
        required: true,
      },
      {
        key: "endsAt",
        label: "Fin de jornada",
        type: "time",
        default: "17:00",
        required: true,
      },
      {
        key: "workingDays",
        label: "Días laborables",
        default: "1,2,3,4,5",
        hint: "0: domingo · 1: lunes … 6: sábado",
        required: true,
      },
      active,
    ],
  },
  facilities: {
    key: "facilities",
    title: "Consultorios y habitaciones",
    singular: "instalación",
    description: "Espacios organizados para una atención tranquila.",
    permission: "infrastructure",
    columns: [
      { key: "name", label: "Espacio" },
      { key: "kind", label: "Tipo" },
      { key: "location", label: "Ubicación" },
      { key: "status", label: "Estado operativo" },
      { key: "active", label: "Registro" },
    ],
    fields: [
      { ...name, label: "Nombre del espacio" },
      {
        key: "kind",
        label: "Tipo",
        options: ["Consultorio", "Habitación"],
        default: "Consultorio",
        required: true,
      },
      {
        key: "location",
        label: "Ubicación",
        default: "Planta baja",
        required: true,
      },
      {
        key: "status",
        label: "Estado",
        options: ["Disponible", "Mantenimiento", "Limpieza", "Ocupada"],
        default: "Disponible",
        required: true,
      },
      active,
    ],
  },
  services: {
    key: "services",
    title: "Servicios",
    singular: "servicio",
    description: "Consultas y procedimientos con duración y precio definidos.",
    permission: "services",
    columns: [
      { key: "name", label: "Servicio" },
      { key: "specialty", label: "Especialidad" },
      { key: "durationMinutes", label: "Duración (min)" },
      { key: "price", label: "Precio" },
      { key: "active", label: "Estado" },
    ],
    fields: [
      { ...name, label: "Nombre del servicio" },
      { key: "specialty", label: "Especialidad", default: "Medicina general" },
      {
        key: "durationMinutes",
        label: "Duración en minutos",
        type: "number",
        min: 5,
        max: 480,
        default: 30,
        required: true,
      },
      {
        key: "price",
        label: "Precio MXN",
        type: "number",
        min: 0,
        max: 1000000,
        default: 650,
        required: true,
      },
      active,
    ],
  },
  companies: {
    key: "companies",
    title: "Empresas y convenios",
    singular: "empresa",
    description: "Convenios, contactos y vigencia de la relación empresarial.",
    permission: "companies",
    columns: [
      { key: "name", label: "Empresa" },
      { key: "rfc", label: "RFC" },
      { key: "contact", label: "Contacto" },
      { key: "validUntil", label: "Vigencia" },
      { key: "active", label: "Estado" },
    ],
    fields: [
      { ...name, label: "Razón social" },
      { key: "rfc", label: "RFC" },
      { key: "contact", label: "Contacto principal" },
      { key: "email", label: "Correo", type: "email" },
      { key: "phone", label: "Teléfono" },
      { key: "validUntil", label: "Vigencia", type: "date" },
      {
        key: "agreement",
        label: "Servicios contratados y condiciones",
        type: "textarea",
      },
      active,
    ],
  },
  users: {
    key: "users",
    title: "Usuarios",
    singular: "usuario",
    description: "Cuentas, accesos y responsabilidad dentro de la clínica.",
    permission: "users",
    columns: [
      { key: "name", label: "Usuario" },
      { key: "username", label: "Cuenta" },
      { key: "roles", label: "Rol" },
      { key: "lastAccess", label: "Último acceso" },
      { key: "active", label: "Estado" },
    ],
    fields: [
      name,
      { key: "username", label: "Nombre de usuario", required: true },
      { key: "email", label: "Correo", type: "email" },
      {
        key: "roles",
        label: "Rol",
        options: [
          "Superadministrador",
          "Administrador general",
          "Administrador de usuarios",
          "Administración financiera",
          "Administración clínica",
          "Auditor",
          "Soporte",
          "Recepción",
          "Médico",
          "Paciente",
          "Empresa",
        ],
        required: true,
      },
      {
        key: "patientId",
        label: "Paciente asociado",
        lookup: "patients",
        hint: "Requerido para el rol Paciente.",
      },
      {
        key: "doctorId",
        label: "Médico asociado",
        lookup: "doctors",
        hint: "Requerido para el rol Médico.",
      },
      {
        key: "companyId",
        label: "Empresa asociada",
        lookup: "companies",
        hint: "Requerido para el rol Empresa.",
      },
      active,
      {
        key: "password",
        label: "Contraseña inicial",
        type: "password",
        required: true,
        hint: "15 a 128 caracteres, mayúscula, minúscula y número. Cuenta individual.",
      },
    ],
  },
  payments: {
    key: "payments",
    title: "Pagos",
    singular: "pago",
    description: "Cobros registrados, importes y comprobantes internos.",
    permission: "payments",
    columns: [
      { key: "folio", label: "Folio" },
      { key: "patientName", label: "Paciente" },
      { key: "concept", label: "Concepto" },
      { key: "amount", label: "Importe" },
      { key: "method", label: "Método" },
      { key: "status", label: "Estado" },
    ],
    fields: [
      {
        key: "companyId",
        label: "Convenio que cubre el pago (opcional)",
        lookup: "companies",
        hint: "Los pagos privados no son visibles para empresas. Requerido para el método Convenio.",
      },
      {
        key: "patientId",
        label: "Paciente",
        lookup: "patients",
        required: true,
      },
      { key: "concept", label: "Concepto", required: true },
      {
        key: "amount",
        label: "Importe MXN",
        type: "number",
        min: 0.01,
        max: 1000000,
        required: true,
      },
      {
        key: "method",
        label: "Método",
        options: ["Efectivo", "Tarjeta", "Transferencia", "Convenio"],
        default: "Efectivo",
        required: true,
      },
      {
        key: "status",
        label: "Estado",
        options: ["Pagado", "Pendiente"],
        default: "Pagado",
        required: true,
      },
    ],
  },
};
